controller_manager:
  ros__parameters:
    update_rate: 20  # Hz

    robot_base_control:
      type: diff_drive_controllerDiffDriveController

    scara_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      
      # Other controllers
      
/**/robot_base_control:
  ros__parameters:
    type: diff_drive_controllerDiffDriveController
    use_stamped_vel: false
    use_sim_time: true
    publish_rate: 50.0
    left_wheel_names: [wheel_link_joint, wheel_w2_link_joint]
    right_wheel_names: [wheel_w3_link_joint, wheel_w4_link_joint]
    wheel_separation: 1.90
    wheel_radius: 0.30
    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: -1.0
    # Base frame_id
    base_frame_id: base_footprint
    # odom tf will be published by direct laser odometry
    enable_odom_tf: true
    # Publish limited velocity
    publish_limited_velocity: true
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 3.0
        has_acceleration_limits: true
        max_acceleration: 3.0
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 3.0
        has_acceleration_limits: true
        max_acceleration: 3.0
        
        
/**/scara_controller:
  ros__parameters:
    joints:
      - arm_cilynder_1_link_joint
      - cylinder_jnt_1_link_joint
      - arm_cilynder_2_link_joint
      - hand_cylinder_link_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      - effort
    allow_nonzero_velocity_at_trajectory_end: true
/**/gripper_controller:
  ros__parameters:
    joints:
      - back_finger_link_joint
      - front_finger_link_joint
      - left_finger_link_joint
      - right_finger_link_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      - effort
    allow_nonzero_velocity_at_trajectory_end: true